from typing import List


def _median_sep_index(lst: List, l: int, r: int) -> int: ...
def introsort(lst: List, l: int, r: int) -> None: ...
def optimized_introsort(lst: List, l: int, r: int) -> None: ...
