from typing import List, Callable, Tuple


def random_sep_index(lst: List, l: int, r: int) -> int: ...
def median_sep_index(lst: List, l: int, r: int) -> int: ...
def partition(lst: List, l: int, r: int, index_func: Callable[[List, int, int], int]) -> int: ...
def three_way_partition(lst: List, l: int, r: int, index_func: Callable[[List, int, int], int]) -> Tuple[int, int]: ...