from typing import List, Tuple, Callable

def _random_sep_index(lst: List, l: int, r: int) -> int: ...
def _partition(lst: List, l: int, r: int, index_func: Callable[[List, int, int], int]) -> int: ...
def _3_way_partition(lst: List, l: int, r: int, index_func: Callable[[List, int, int], int]) -> Tuple[int, int]: ...
def quick_sort_random(lst: List, l: int, r: int) -> None: ...
def quick_sort_no_tail_recursion(lst: List, l: int, r: int) -> None: ...
def quick_sort_no_recursion(lst: List, l: int, r: int) -> None: ...
def quick_sort_3_way_partition(lst: List, l: int, r: int) -> None: ...
