from typing import List


def quick_sort_random(lst: List, l: int, r: int) -> None: ...
def quick_sort_no_tail_recursion(lst: List, l: int, r: int) -> None: ...
def quick_sort_no_recursion(lst: List, l: int, r: int) -> None: ...
def quick_sort_3_way_partition(lst: List, l: int, r: int) -> None: ...
